-- Generated by github.com/davyxu/tabtoy
-- Version: 

---@class Config
---@field FightCommand FightCommandDefine[] FightCommand
---@field GoodsCommand GoodsCommandDefine[] GoodsCommand
---@field HeroCommand HeroCommandDefine[] HeroCommand
---@field TestSheet TestSheetDefine[] TestSheet
---@field TestCommand TestCommandDefine[] TestCommand
---@field SealwareCommand SealwareCommandDefine[] SealwareCommand
---@field LevelCommand LevelCommandDefine[] LevelCommand
---@field TestCommand2 TestCommand2Define[] TestCommand2


---@class WaveGroup
---@field id number 
---@field count number 
---@field index number 
---@field test number 
---@field time number 
---@field delay number 


---@class Vec3
---@field x number 
---@field y number 
---@field z number 


---@class Vec4
---@field x number 
---@field y number 
---@field z number 
---@field v number 


---@class attr
---@field attrid number 
---@field attrnum number 
---@field attrper number 


---@class composeeffect
---@field attr string 
---@field per number 


---@class condition
---@field mainpart number 條件主體(1:自身;2:怪物ID;3:英雄類型;4:怪物類型;5:路徑;6:龍寶寶;)
---@field conditionpattern number 條件類型(1:血量;2:數量;3:長度;4:波數;)
---@field judge number 判定(1:大於;2:大於等於;3:等於;4:小於等於;5:小於;)
---@field parameter number 參數


---@class incident
---@field mainpart number 主體(1:自身;2:怪物ID;)
---@field eventpattern number 事件(1:技能ID;2:說話;)
---@field parameter number 參數
---@field talk string 說話，配置文本字串
---@field target number 目標(1:無;2:怪物ID;)
---@field targetparameter number 參數


---@class costlist
---@field propertyid number 
---@field num number 


---@class reward
---@field goodsid number 
---@field num number 


---@class Vec2
---@field x number 
---@field y number 


---@class strike
---@field condition number 條件類型(1:自身血量;2:友方數量;3:暴击触发;4：到达终点触发)
---@field judge number 判定(1:大於;2:大於等於;3:等於;4:小於等於;5:小於;)
---@field parameter number 參數
---@field rate number 暴击触发/到达终点只需要填概率


---@class trammelsskill
---@field heronum number 
---@field skillid number 


---@class dropItems
---@field itemid number 
---@field count number 
---@field weight number 
---@field minNum number 


---@class guideparameter
---@field parameter1 number 
---@field parameter2 string 


---@class limitparameter
---@field intlimit number 
---@field stringlimit string 


---@class herodata
---@field heroid number 
---@field herocolor number 
---@field herolevel number 
---@field heronum number 


---@class black
---@field x number 
---@field y number 
---@field z number 
---@field speed number 
---@field duration number 


---@class numweight
---@field leveupnum number 
---@field weight number 


---@class guidecondition
---@field cond string 
---@field num number 
---@field id number 


---@class guidePicPos
---@field x number 
---@field y number 


---@class guidelimit
---@field cond string 
---@field num number 
---@field id number 


---@class groups
---@field groupid string 
---@field num number 


---@class talentrevise
---@field name string 对应标签页的这个标签
---@field pattern number 修改类型（1:替代；2:新增；3:数值增加；4：数值乘积）新增只应用于数组中
---@field magicnum number 表示修改的是第几项魔法，可为空，空值表示第一项，只在修改魔法列表时生效 修改的魔法与项数对应
---@field seriesnum number 表示要改的是第几个数列，可为空，空值表示不是数组，但是如果是数据类型是数组则不能留空
---@field seriesname string 数列名，可为空，空值表示直接修改数值，无数组名
---@field parameter string 


---@class boom
---@field id number 
---@field num number 可为空，空值表示只要暴击就能触发，不限次数。 在计数时，技能本身那次不算


---@class direction
---@field fx number 可为空，空值表示以英雄为中心，找参照点的方向，以12点为1，顺时针，共计8个方向（1-8）
---@field hero number 可为空，空值表示以英雄为中心，找参照点的距离，在这个方向上距英雄几个格子距离的点，为参照点
---@field fx2 number 可为空，以12点为1，顺时针，共计8个方向（1-8）
---@field linenum number 可为空，参照点方向上的格子数量（连续）


---@class cash
---@field language string 
---@field pattern number 
---@field price number 


---@class HireHeroLimit
---@field herocolor number 雇佣任务用
---@field weight number 


---@class Consumption
---@field id number 商店，限时购买中，商品筛选机制使用，配置与玩家等级配置表中
---@field value number 


---@class typeRandom
---@field attrid number 
---@field weight number 


---@class ValueRandom
---@field num number 如果对应的属性是固定值，则固定加成；如果对应的属性是比例值，则比例加成
---@field weight number 


---@class FightCommandDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字
---@field speed number {1}加速倍数


---@class GoodsCommandDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字；
---@field parameter reward[] {1}获得物品ID、获得物品数量； 注意： 1.物品类型：资产、装备，需要各自单独配置，即不可与其他类型物品在同一个数据格中混合配置； 2.经验，获得的数量不能为负，为负时不生效； 3.装备，涉及到带有唯一ID，原则上配置获得数量不能超过99


---@class HeroCommandDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字；涉及到带有唯一ID的物品，原则配置获得数量不能超过99，如英雄
---@field parameter herodata[] {1}依次为英雄ID、英雄品质、英雄等级、英雄数量； 注意： 1.英雄品质、等级只能配置比初始值高；如果其中一项未填写，则按对应ID的默认数据输入； 2.英雄涉及到带有唯一ID，原则配置获得数量不能超过99


---@class TestSheetDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字
---@field sealwareId number {1}封印物ID


---@class TestCommandDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字
---@field levelId number {1}跳转的关卡ID


---@class SealwareCommandDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字
---@field sealwareId number {1}封印物ID


---@class LevelCommandDefine
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字
---@field levelId number {1}跳转的关卡ID


---@class TestCommand2Define
---@field sort number {1}命令序数
---@field text string {1}命令描述文本；原则上不超过20个字
---@field sealwareId number {1}封印物ID


---@type Config
local tab = {
	FightCommand = {
		{ sort = 1, text = "战斗1倍速", speed = 1 	},
		{ sort = 2, text = "战斗2倍速", speed = 2 	},
		{ sort = 3, text = "战斗3倍速", speed = 3 	},
		{ sort = 4, text = "战斗5倍速", speed = 5 	}
	}, 

	GoodsCommand = {
		{ sort = 1, text = "获得测试装备1、2、3、4", parameter = { { goodsid= 140179001, num= 1 }, { goodsid= 140170002, num= 1 }, { goodsid= 140170003, num= 1 }, { goodsid= 140170004, num= 1 } } 	},
		{ sort = 2, text = "获得金币10000", parameter = { { goodsid= 140160001, num= 10000 } } 	},
		{ sort = 3, text = "获得钻石50", parameter = { { goodsid= 140160002, num= 50 } } 	},
		{ sort = 4, text = "获得金币、钻石各10000", parameter = { { goodsid= 140160001, num= 10000 }, { goodsid= 140160002, num= 10000 } } 	},
		{ sort = 5, text = "获得绝品符文*10", parameter = { { goodsid= 140140005, num= 10 } } 	},
		{ sort = 6, text = "获得4级符文*10", parameter = { { goodsid= 140140003, num= 10 } } 	},
		{ sort = 7, text = "获得破损符文*10", parameter = { { goodsid= 140140000, num= 10 } } 	},
		{ sort = 8, text = "减少金币10000", parameter = { { goodsid= 140160001, num= -10000 } } 	},
		{ sort = 9, text = "每种元素碎片1000", parameter = { { goodsid= 140160005, num= 1000 }, { goodsid= 140160006, num= 1000 }, { goodsid= 140160007, num= 1000 }, { goodsid= 140160008, num= 1000 }, { goodsid= 140160009, num= 1000 } } 	},
		{ sort = 10, text = "灵魂结晶1000", parameter = { { goodsid= 140160004, num= 1000 } } 	},
		{ sort = 11, text = "获得食人魔首領.水*10", parameter = { { goodsid= 140110001, num= 10 } } 	},
		{ sort = 12, text = "减少20把钥匙", parameter = { { goodsid= 140160003, num= -20 } } 	},
		{ sort = 13, text = "获得经验*100000", parameter = { { goodsid= 140160000, num= 100000 } } 	},
		{ sort = 14, text = "获得灵魂结晶*100", parameter = { { goodsid= 140160004, num= 100 } } 	},
		{ sort = 15, text = "获得水之精华*100", parameter = { { goodsid= 140160005, num= 100 } } 	},
		{ sort = 16, text = "获得火之精华*100", parameter = { { goodsid= 140160006, num= 100 } } 	},
		{ sort = 17, text = "获得风之精华*100", parameter = { { goodsid= 140160007, num= 100 } } 	},
		{ sort = 18, text = "获得光之精华*100", parameter = { { goodsid= 140160008, num= 100 } } 	},
		{ sort = 19, text = "获得暗之精华*100", parameter = { { goodsid= 140160009, num= 100 } } 	},
		{ sort = 20, text = "获得深渊水晶*100", parameter = { { goodsid= 140160010, num= 100 } } 	},
		{ sort = 21, text = "获得传奇徽记*100", parameter = { { goodsid= 140160011, num= 100 } } 	},
		{ sort = 22, text = "获得试炼徽记*100", parameter = { { goodsid= 140160012, num= 100 } } 	},
		{ sort = 23, text = "获得荣耀徽记*100", parameter = { { goodsid= 140160013, num= 100 } } 	},
		{ sort = 24, text = "获得魔力水晶*10000", parameter = { { goodsid= 140160014, num= 10000 } } 	},
		{ sort = 25, text = "获得工会经验*100", parameter = { { goodsid= 140160015, num= 100 } } 	},
		{ sort = 26, text = "获得能量*100", parameter = { { goodsid= 140160016, num= 100 } } 	},
		{ sort = 27, text = "获得史诗徽记*100", parameter = { { goodsid= 140160017, num= 100 } } 	},
		{ sort = 28, text = "获得稀有徽记*100", parameter = { { goodsid= 140160018, num= 100 } } 	},
		{ sort = 29, text = "获得普通徽记*100", parameter = { { goodsid= 140160019, num= 100 } } 	},
		{ sort = 30, text = "封印物碎片礼包·大*10", parameter = { { goodsid= 140150000, num= 100 } } 	},
		{ sort = 31, text = "封印物碎片礼包·中*10", parameter = { { goodsid= 140150001, num= 100 } } 	},
		{ sort = 32, text = "封印物碎片礼包·小*10", parameter = { { goodsid= 140150002, num= 100 } } 	},
		{ sort = 33, text = "获得守护龙经验*1000", parameter = { { goodsid= 140160024, num= 1000 } } 	},
		{ sort = 34, text = "100个克拉肯之斧碎片", parameter = { { goodsid= 140110100, num= 100 } } 	},
		{ sort = 35, text = "100个阿涅彌伊之怒碎片", parameter = { { goodsid= 140110101, num= 100 } } 	},
		{ sort = 36, text = "100个加利胡斯金號角碎片", parameter = { { goodsid= 140110102, num= 100 } } 	},
		{ sort = 37, text = "100个海拉鐮刀碎片", parameter = { { goodsid= 140110103, num= 100 } } 	},
		{ sort = 38, text = "100个海神三叉戟碎片", parameter = { { goodsid= 140110104, num= 100 } } 	},
		{ sort = 39, text = "100个潘多拉魔盒碎片", parameter = { { goodsid= 140110105, num= 100 } } 	},
		{ sort = 40, text = "100个克圖格亞之眼碎片", parameter = { { goodsid= 140110106, num= 100 } } 	},
		{ sort = 41, text = "100个巨狼雙魂碎片", parameter = { { goodsid= 140110107, num= 100 } } 	},
		{ sort = 42, text = "100个阿爾忒彌斯之弓碎片", parameter = { { goodsid= 140110108, num= 100 } } 	},
		{ sort = 43, text = "100个拉神寶球碎片", parameter = { { goodsid= 140110109, num= 100 } } 	},
		{ sort = 44, text = "100个原初之眼碎片", parameter = { { goodsid= 140110110, num= 100 } } 	},
		{ sort = 45, text = "100个永恆之槍碎片", parameter = { { goodsid= 140110111, num= 100 } } 	},
		{ sort = 46, text = "100个雷霆之盾碎片", parameter = { { goodsid= 140110112, num= 100 } } 	},
		{ sort = 47, text = "100个鮮血聖杯碎片", parameter = { { goodsid= 140110113, num= 100 } } 	},
		{ sort = 48, text = "100个佛拉格拉克碎片", parameter = { { goodsid= 140110114, num= 100 } } 	},
		{ sort = 49, text = "100个方舟龍骨碎片", parameter = { { goodsid= 140110115, num= 100 } } 	},
		{ sort = 50, text = "100个死靈之書碎片", parameter = { { goodsid= 140110116, num= 100 } } 	},
		{ sort = 51, text = "100个妖精之弓希爾文碎片", parameter = { { goodsid= 140110117, num= 100 } } 	},
		{ sort = 52, text = "100个龍之寶玉奧普碎片", parameter = { { goodsid= 140110118, num= 100 } } 	},
		{ sort = 53, text = "100个赫格尼之劍碎片", parameter = { { goodsid= 140110119, num= 100 } } 	},
		{ sort = 54, text = "100个烈焰之劍雷沃汀碎片", parameter = { { goodsid= 140110120, num= 100 } } 	},
		{ sort = 55, text = "100个神王雷槍碎片", parameter = { { goodsid= 140110121, num= 100 } } 	},
		{ sort = 56, text = "100个雙蛇權杖碎片", parameter = { { goodsid= 140110122, num= 100 } } 	},
		{ sort = 57, text = "100个蛇骨短劍碎片", parameter = { { goodsid= 140110123, num= 100 } } 	},
		{ sort = 58, text = "100个羊靈頭顱碎片", parameter = { { goodsid= 140110124, num= 100 } } 	},
		{ sort = 59, text = "100个世界樹根碎片", parameter = { { goodsid= 140110125, num= 100 } } 	},
		{ sort = 60, text = "100个巨獸犄角碎片", parameter = { { goodsid= 140110126, num= 100 } } 	},
		{ sort = 61, text = "100个鑽頭劍碎片", parameter = { { goodsid= 140110127, num= 100 } } 	},
		{ sort = 62, text = "100个伊利丹爾古碎片", parameter = { { goodsid= 140110128, num= 100 } } 	},
		{ sort = 63, text = "100个鹿靈頭骨碎片", parameter = { { goodsid= 140110129, num= 100 } } 	},
		{ sort = 64, text = "100个靈魂燈籠碎片", parameter = { { goodsid= 140110130, num= 100 } } 	},
		{ sort = 65, text = "100个末地寶珠碎片", parameter = { { goodsid= 140110131, num= 100 } } 	},
		{ sort = 66, text = "100个帶刺炎尾碎片", parameter = { { goodsid= 140110132, num= 100 } } 	},
		{ sort = 67, text = "100个胡狼頭盔碎片", parameter = { { goodsid= 140110133, num= 100 } } 	},
		{ sort = 68, text = "100个隼型頭盔碎片", parameter = { { goodsid= 140110134, num= 100 } } 	},
		{ sort = 69, text = "100个石質蛇首碎片", parameter = { { goodsid= 140110135, num= 100 } } 	},
		{ sort = 70, text = "100个神秘戒指碎片", parameter = { { goodsid= 140110136, num= 100 } } 	},
		{ sort = 71, text = "100个金質聖甲蟲碎片", parameter = { { goodsid= 140110137, num= 100 } } 	},
		{ sort = 72, text = "100个銜尾蛇戒指碎片", parameter = { { goodsid= 140110138, num= 100 } } 	},
		{ sort = 73, text = "100个懷特的髕骨碎片", parameter = { { goodsid= 140110139, num= 100 } } 	},
		{ sort = 74, text = "100个妖狐面具碎片", parameter = { { goodsid= 140110140, num= 100 } } 	},
		{ sort = 75, text = "100个血魔披風碎片", parameter = { { goodsid= 140110141, num= 100 } } 	},
		{ sort = 76, text = "100个神秘名單碎片", parameter = { { goodsid= 140110142, num= 100 } } 	},
		{ sort = 77, text = "100个渡鴉羽毛碎片", parameter = { { goodsid= 140110143, num= 100 } } 	},
		{ sort = 78, text = "100个詭異石盤碎片", parameter = { { goodsid= 140110144, num= 100 } } 	},
		{ sort = 79, text = "100个水晶頭骨碎片", parameter = { { goodsid= 140110145, num= 100 } } 	},
		{ sort = 80, text = "100个人身獅面像碎片", parameter = { { goodsid= 140110146, num= 100 } } 	},
		{ sort = 81, text = "获得金币100W", parameter = { { goodsid= 140160001, num= 1000000 } } 	},
		{ sort = 82, text = "10000个靈魂結晶", parameter = { { goodsid= 140160004, num= 10000 } } 	},
		{ sort = 83, text = "10000个水之精華", parameter = { { goodsid= 140160005, num= 10000 } } 	},
		{ sort = 84, text = "10000个火之精華", parameter = { { goodsid= 140160006, num= 10000 } } 	},
		{ sort = 85, text = "10000个風之精華", parameter = { { goodsid= 140160007, num= 10000 } } 	},
		{ sort = 86, text = "10000个光之精華", parameter = { { goodsid= 140160008, num= 10000 } } 	},
		{ sort = 87, text = "10000个暗之精華", parameter = { { goodsid= 140160009, num= 10000 } } 	},
		{ sort = 88, text = "10000个深淵水晶", parameter = { { goodsid= 140160010, num= 10000 } } 	},
		{ sort = 89, text = "10000个傳奇徽記", parameter = { { goodsid= 140160011, num= 10000 } } 	},
		{ sort = 90, text = "1000个試煉徽記", parameter = { { goodsid= 140160012, num= 10000 } } 	},
		{ sort = 91, text = "10000个榮耀徽記", parameter = { { goodsid= 140160013, num= 10000 } } 	},
		{ sort = 92, text = "10000个魔力水晶", parameter = { { goodsid= 140160014, num= 10000 } } 	},
		{ sort = 93, text = "10000个公會經驗", parameter = { { goodsid= 140160015, num= 10000 } } 	},
		{ sort = 94, text = "10000个能量", parameter = { { goodsid= 140160016, num= 10000 } } 	},
		{ sort = 95, text = "10000个史詩徽記", parameter = { { goodsid= 140160017, num= 10000 } } 	},
		{ sort = 96, text = "10000个稀有徽記", parameter = { { goodsid= 140160018, num= 10000 } } 	},
		{ sort = 97, text = "10000个普通徽記", parameter = { { goodsid= 140160019, num= 10000 } } 	},
		{ sort = 98, text = "10000个海圖傳令", parameter = { { goodsid= 140160020, num= 10000 } } 	},
		{ sort = 99, text = "10个單抽祭品", parameter = { { goodsid= 140160022, num= 10 } } 	},
		{ sort = 100, text = "10个五連抽祭品", parameter = { { goodsid= 140160023, num= 10 } } 	},
		{ sort = 101, text = "10000个守护龙经验", parameter = { { goodsid= 140160024, num= 10000 } } 	},
		{ sort = 102, text = "10000个战令经验", parameter = { { goodsid= 140160025, num= 10000 } } 	},
		{ sort = 103, text = "10000个封印物碎片礼包·大", parameter = { { goodsid= 140150000, num= 10000 } } 	},
		{ sort = 104, text = "10000个封印物碎片礼包·中", parameter = { { goodsid= 140150001, num= 10000 } } 	},
		{ sort = 105, text = "10000个封印物碎片礼包·小", parameter = { { goodsid= 140150002, num= 10000 } } 	}
	}, 

	TestSheet = {
		{ sort = 1, text = "克拉肯之斧", sealwareId = 200110001 	},
		{ sort = 2, text = "阿涅彌伊之怒", sealwareId = 200110002 	},
		{ sort = 3, text = "加利胡斯金號角", sealwareId = 200110003 	},
		{ sort = 4, text = "海拉鐮刀", sealwareId = 200110004 	},
		{ sort = 5, text = "海神三叉戟", sealwareId = 200110005 	},
		{ sort = 6, text = "潘多拉魔盒", sealwareId = 200110006 	},
		{ sort = 7, text = "克圖格亞之眼", sealwareId = 200110007 	},
		{ sort = 8, text = "巨狼雙魂", sealwareId = 200110008 	},
		{ sort = 9, text = "阿爾忒彌斯之弓", sealwareId = 200110009 	},
		{ sort = 10, text = "拉神寶球", sealwareId = 200110010 	},
		{ sort = 11, text = "原初之眼", sealwareId = 200110011 	},
		{ sort = 12, text = "永恆之槍", sealwareId = 200110012 	},
		{ sort = 13, text = "雷霆之盾", sealwareId = 200210001 	},
		{ sort = 14, text = "鮮血聖杯", sealwareId = 200210002 	},
		{ sort = 15, text = "佛拉格拉克", sealwareId = 200210003 	},
		{ sort = 16, text = "世界樹根", sealwareId = 200210004 	},
		{ sort = 17, text = "死靈之書", sealwareId = 200210005 	},
		{ sort = 18, text = "妖精之弓希爾文", sealwareId = 200210006 	},
		{ sort = 19, text = "龍之寶玉奧普", sealwareId = 200210007 	},
		{ sort = 20, text = "赫格尼之劍", sealwareId = 200210008 	},
		{ sort = 21, text = "烈焰之劍雷沃汀", sealwareId = 200210009 	},
		{ sort = 22, text = "神王雷槍", sealwareId = 200210010 	},
		{ sort = 23, text = "雙蛇權杖", sealwareId = 200210011 	},
		{ sort = 24, text = "蛇骨短劍", sealwareId = 200210012 	},
		{ sort = 25, text = "羊靈頭顱", sealwareId = 200210013 	},
		{ sort = 26, text = "方舟龍骨", sealwareId = 200210014 	},
		{ sort = 27, text = "巨獸犄角", sealwareId = 200210015 	},
		{ sort = 28, text = "鑽頭劍", sealwareId = 200210016 	},
		{ sort = 29, text = "伊利丹爾古", sealwareId = 200210017 	},
		{ sort = 30, text = "鹿靈頭骨", sealwareId = 200210018 	},
		{ sort = 31, text = "靈魂燈籠", sealwareId = 200210019 	},
		{ sort = 32, text = "末地寶珠", sealwareId = 200210020 	},
		{ sort = 33, text = "帶刺炎尾", sealwareId = 200210021 	},
		{ sort = 34, text = "胡狼頭盔", sealwareId = 200210022 	},
		{ sort = 35, text = "隼型頭盔", sealwareId = 200210023 	},
		{ sort = 36, text = "石質蛇首", sealwareId = 200210024 	},
		{ sort = 37, text = "神秘戒指", sealwareId = 200210025 	},
		{ sort = 38, text = "金質聖甲蟲", sealwareId = 200210026 	},
		{ sort = 39, text = "銜尾蛇戒指", sealwareId = 200210027 	},
		{ sort = 40, text = "懷特的髕骨", sealwareId = 200210028 	},
		{ sort = 41, text = "妖狐面具", sealwareId = 200210029 	},
		{ sort = 42, text = "血魔披風", sealwareId = 200210030 	},
		{ sort = 43, text = "神秘名單", sealwareId = 200210031 	},
		{ sort = 44, text = "渡鴉羽毛", sealwareId = 200210032 	},
		{ sort = 45, text = "詭異石盤", sealwareId = 200210033 	},
		{ sort = 46, text = "水晶頭骨", sealwareId = 200210034 	},
		{ sort = 47, text = "人身獅面像", sealwareId = 200210035 	},
		{ sort = 48, text = "海妖豎琴", sealwareId = 200210036 	},
		{ sort = 49, text = "賽巴的石頭", sealwareId = 200210037 	},
		{ sort = 50, text = "雷獸利角", sealwareId = 200210038 	},
		{ sort = 51, text = "魔龍毒牙", sealwareId = 200210039 	},
		{ sort = 52, text = "瓶裝龍息", sealwareId = 200210040 	},
		{ sort = 53, text = "透明蟲翅", sealwareId = 200210041 	},
		{ sort = 54, text = "地精戰錘", sealwareId = 200210042 	},
		{ sort = 55, text = "精靈短弓", sealwareId = 200210043 	},
		{ sort = 56, text = "捕夢網", sealwareId = 200210044 	},
		{ sort = 57, text = "酒館鑰匙", sealwareId = 200210045 	},
		{ sort = 58, text = "詭異布偶", sealwareId = 200210046 	},
		{ sort = 59, text = "黃金鎧甲", sealwareId = 200210047 	},
		{ sort = 60, text = "星座紋章", sealwareId = 200210048 	},
		{ sort = 61, text = "銘文石碑", sealwareId = 200210049 	},
		{ sort = 62, text = "花生狀石塊", sealwareId = 200210050 	}
	}, 

	TestCommand = {
		{ sort = 1, text = "跳转到关卡1-1", levelId = 170210001 	},
		{ sort = 2, text = "跳转到关卡1-6", levelId = 170210006 	},
		{ sort = 3, text = "跳转到关卡1-10", levelId = 170210010 	},
		{ sort = 4, text = "跳转到关卡2-1", levelId = 170210011 	},
		{ sort = 5, text = "跳转到关卡2-6", levelId = 170210016 	},
		{ sort = 6, text = "跳转到关卡2-11", levelId = 170210021 	},
		{ sort = 7, text = "跳转到关卡2-16", levelId = 170210026 	},
		{ sort = 8, text = "跳转到关卡2-20", levelId = 170210030 	},
		{ sort = 9, text = "跳转到关卡3-1", levelId = 170210031 	},
		{ sort = 10, text = "跳转到关卡3-6", levelId = 170210036 	},
		{ sort = 11, text = "跳转到关卡3-11", levelId = 170210041 	},
		{ sort = 12, text = "跳转到关卡3-16", levelId = 170210046 	},
		{ sort = 13, text = "跳转到关卡4-1", levelId = 170210051 	},
		{ sort = 14, text = "跳转到关卡4-6", levelId = 170210056 	},
		{ sort = 15, text = "跳转到关卡4-11", levelId = 170210061 	},
		{ sort = 16, text = "跳转到关卡4-16", levelId = 170210066 	},
		{ sort = 17, text = "跳转到关卡5-1", levelId = 170210071 	},
		{ sort = 18, text = "跳转到关卡5-6", levelId = 170210076 	},
		{ sort = 19, text = "跳转到关卡5-11", levelId = 170210081 	},
		{ sort = 20, text = "跳转到关卡5-16", levelId = 170210086 	},
		{ sort = 21, text = "跳转到关卡6-1", levelId = 170210091 	},
		{ sort = 22, text = "跳转到关卡6-6", levelId = 170210096 	},
		{ sort = 23, text = "跳转到关卡6-11", levelId = 170210101 	},
		{ sort = 24, text = "跳转到关卡6-16", levelId = 170210106 	},
		{ sort = 25, text = "跳转到关卡7-1", levelId = 170210111 	},
		{ sort = 26, text = "跳转到关卡7-6", levelId = 170210116 	},
		{ sort = 27, text = "跳转到关卡7-11", levelId = 170210121 	},
		{ sort = 28, text = "跳转到关卡7-16", levelId = 170210126 	},
		{ sort = 29, text = "跳转到关卡8-1", levelId = 170210131 	},
		{ sort = 30, text = "跳转到关卡8-6", levelId = 170210136 	},
		{ sort = 31, text = "跳转到关卡8-11", levelId = 170210141 	},
		{ sort = 32, text = "跳转到关卡8-16", levelId = 170210146 	},
		{ sort = 33, text = "跳转到关卡9-1", levelId = 170210151 	},
		{ sort = 34, text = "跳转到关卡9-6", levelId = 170210156 	},
		{ sort = 35, text = "跳转到关卡9-11", levelId = 170210161 	},
		{ sort = 36, text = "跳转到关卡9-16", levelId = 170210166 	},
		{ sort = 37, text = "跳转到关卡9-17", levelId = 170210167 	},
		{ sort = 38, text = "跳转到关卡9-18", levelId = 170210168 	},
		{ sort = 39, text = "跳转到关卡9-19", levelId = 170210169 	},
		{ sort = 40, text = "跳转到关卡9-20", levelId = 170210170 	}
	}, 

	SealwareCommand = {
		{ sort = 1, text = "克拉肯之斧", sealwareId = 200110001 	},
		{ sort = 2, text = "阿涅彌伊之怒", sealwareId = 200110002 	},
		{ sort = 3, text = "加利胡斯金號角", sealwareId = 200110003 	},
		{ sort = 4, text = "海拉鐮刀", sealwareId = 200110004 	},
		{ sort = 5, text = "海神三叉戟", sealwareId = 200110005 	},
		{ sort = 6, text = "潘多拉魔盒", sealwareId = 200110006 	},
		{ sort = 7, text = "克圖格亞之眼", sealwareId = 200110007 	},
		{ sort = 8, text = "巨狼雙魂", sealwareId = 200110008 	},
		{ sort = 9, text = "阿爾忒彌斯之弓", sealwareId = 200110009 	},
		{ sort = 10, text = "拉神寶球", sealwareId = 200110010 	},
		{ sort = 11, text = "原初之眼", sealwareId = 200110011 	},
		{ sort = 12, text = "永恆之槍", sealwareId = 200110012 	},
		{ sort = 13, text = "雷霆之盾", sealwareId = 200210001 	},
		{ sort = 14, text = "鮮血聖杯", sealwareId = 200210002 	},
		{ sort = 15, text = "佛拉格拉克", sealwareId = 200210003 	},
		{ sort = 16, text = "世界樹根", sealwareId = 200210004 	},
		{ sort = 17, text = "死靈之書", sealwareId = 200210005 	},
		{ sort = 18, text = "妖精之弓希爾文", sealwareId = 200210006 	},
		{ sort = 19, text = "龍之寶玉奧普", sealwareId = 200210007 	},
		{ sort = 20, text = "赫格尼之劍", sealwareId = 200210008 	},
		{ sort = 21, text = "烈焰之劍雷沃汀", sealwareId = 200210009 	},
		{ sort = 22, text = "神王雷槍", sealwareId = 200210010 	},
		{ sort = 23, text = "雙蛇權杖", sealwareId = 200210011 	},
		{ sort = 24, text = "蛇骨短劍", sealwareId = 200210012 	},
		{ sort = 25, text = "羊靈頭顱", sealwareId = 200210013 	},
		{ sort = 26, text = "方舟龍骨", sealwareId = 200210014 	},
		{ sort = 27, text = "巨獸犄角", sealwareId = 200210015 	},
		{ sort = 28, text = "鑽頭劍", sealwareId = 200210016 	},
		{ sort = 29, text = "伊利丹爾古", sealwareId = 200210017 	},
		{ sort = 30, text = "鹿靈頭骨", sealwareId = 200210018 	},
		{ sort = 31, text = "靈魂燈籠", sealwareId = 200210019 	},
		{ sort = 32, text = "末地寶珠", sealwareId = 200210020 	},
		{ sort = 33, text = "帶刺炎尾", sealwareId = 200210021 	},
		{ sort = 34, text = "胡狼頭盔", sealwareId = 200210022 	},
		{ sort = 35, text = "隼型頭盔", sealwareId = 200210023 	},
		{ sort = 36, text = "石質蛇首", sealwareId = 200210024 	},
		{ sort = 37, text = "神秘戒指", sealwareId = 200210025 	},
		{ sort = 38, text = "金質聖甲蟲", sealwareId = 200210026 	},
		{ sort = 39, text = "銜尾蛇戒指", sealwareId = 200210027 	},
		{ sort = 40, text = "懷特的髕骨", sealwareId = 200210028 	},
		{ sort = 41, text = "妖狐面具", sealwareId = 200210029 	},
		{ sort = 42, text = "血魔披風", sealwareId = 200210030 	},
		{ sort = 43, text = "神秘名單", sealwareId = 200210031 	},
		{ sort = 44, text = "渡鴉羽毛", sealwareId = 200210032 	},
		{ sort = 45, text = "詭異石盤", sealwareId = 200210033 	},
		{ sort = 46, text = "水晶頭骨", sealwareId = 200210034 	},
		{ sort = 47, text = "人身獅面像", sealwareId = 200210035 	},
		{ sort = 48, text = "海妖豎琴", sealwareId = 200210036 	},
		{ sort = 49, text = "賽巴的石頭", sealwareId = 200210037 	},
		{ sort = 50, text = "雷獸利角", sealwareId = 200210038 	},
		{ sort = 51, text = "魔龍毒牙", sealwareId = 200210039 	},
		{ sort = 52, text = "瓶裝龍息", sealwareId = 200210040 	},
		{ sort = 53, text = "透明蟲翅", sealwareId = 200210041 	},
		{ sort = 54, text = "地精戰錘", sealwareId = 200210042 	},
		{ sort = 55, text = "精靈短弓", sealwareId = 200210043 	},
		{ sort = 56, text = "捕夢網", sealwareId = 200210044 	},
		{ sort = 57, text = "酒館鑰匙", sealwareId = 200210045 	},
		{ sort = 58, text = "詭異布偶", sealwareId = 200210046 	},
		{ sort = 59, text = "黃金鎧甲", sealwareId = 200210047 	},
		{ sort = 60, text = "星座紋章", sealwareId = 200210048 	},
		{ sort = 61, text = "銘文石碑", sealwareId = 200210049 	},
		{ sort = 62, text = "花生狀石塊", sealwareId = 200210050 	}
	}, 

	LevelCommand = {
		{ sort = 1, text = "跳转到关卡1-1", levelId = 170210001 	},
		{ sort = 2, text = "跳转到关卡1-6", levelId = 170210006 	},
		{ sort = 3, text = "跳转到关卡1-10", levelId = 170210010 	},
		{ sort = 4, text = "跳转到关卡2-1", levelId = 170210011 	},
		{ sort = 5, text = "跳转到关卡2-6", levelId = 170210016 	},
		{ sort = 6, text = "跳转到关卡2-11", levelId = 170210021 	},
		{ sort = 7, text = "跳转到关卡2-16", levelId = 170210026 	},
		{ sort = 8, text = "跳转到关卡2-20", levelId = 170210030 	},
		{ sort = 9, text = "跳转到关卡3-1", levelId = 170210031 	},
		{ sort = 10, text = "跳转到关卡3-6", levelId = 170210036 	},
		{ sort = 11, text = "跳转到关卡3-11", levelId = 170210041 	},
		{ sort = 12, text = "跳转到关卡3-16", levelId = 170210046 	},
		{ sort = 13, text = "跳转到关卡4-1", levelId = 170210051 	},
		{ sort = 14, text = "跳转到关卡4-6", levelId = 170210056 	},
		{ sort = 15, text = "跳转到关卡4-11", levelId = 170210061 	},
		{ sort = 16, text = "跳转到关卡4-16", levelId = 170210066 	},
		{ sort = 17, text = "跳转到关卡5-1", levelId = 170210071 	},
		{ sort = 18, text = "跳转到关卡5-6", levelId = 170210076 	},
		{ sort = 19, text = "跳转到关卡5-11", levelId = 170210081 	},
		{ sort = 20, text = "跳转到关卡5-16", levelId = 170210086 	},
		{ sort = 21, text = "跳转到关卡6-1", levelId = 170210091 	},
		{ sort = 22, text = "跳转到关卡6-6", levelId = 170210096 	},
		{ sort = 23, text = "跳转到关卡6-11", levelId = 170210101 	},
		{ sort = 24, text = "跳转到关卡6-16", levelId = 170210106 	},
		{ sort = 25, text = "跳转到关卡7-1", levelId = 170210111 	},
		{ sort = 26, text = "跳转到关卡7-6", levelId = 170210116 	},
		{ sort = 27, text = "跳转到关卡7-11", levelId = 170210121 	},
		{ sort = 28, text = "跳转到关卡7-16", levelId = 170210126 	},
		{ sort = 29, text = "跳转到关卡8-1", levelId = 170210131 	},
		{ sort = 30, text = "跳转到关卡8-6", levelId = 170210136 	},
		{ sort = 31, text = "跳转到关卡8-11", levelId = 170210141 	},
		{ sort = 32, text = "跳转到关卡8-16", levelId = 170210146 	},
		{ sort = 33, text = "跳转到关卡9-1", levelId = 170210151 	},
		{ sort = 34, text = "跳转到关卡9-6", levelId = 170210156 	},
		{ sort = 35, text = "跳转到关卡9-11", levelId = 170210161 	},
		{ sort = 36, text = "跳转到关卡9-16", levelId = 170210166 	},
		{ sort = 37, text = "跳转到关卡9-17", levelId = 170210167 	},
		{ sort = 38, text = "跳转到关卡9-18", levelId = 170210168 	},
		{ sort = 39, text = "跳转到关卡9-19", levelId = 170210169 	},
		{ sort = 40, text = "跳转到关卡9-20", levelId = 170210170 	}
	}, 

	TestCommand2 = {
		{ sort = 1, text = "克拉肯之斧", sealwareId = 200110001 	},
		{ sort = 2, text = "阿涅彌伊之怒", sealwareId = 200110002 	},
		{ sort = 3, text = "加利胡斯金號角", sealwareId = 200110003 	},
		{ sort = 4, text = "海拉鐮刀", sealwareId = 200110004 	},
		{ sort = 5, text = "海神三叉戟", sealwareId = 200110005 	},
		{ sort = 6, text = "潘多拉魔盒", sealwareId = 200110006 	},
		{ sort = 7, text = "克圖格亞之眼", sealwareId = 200110007 	},
		{ sort = 8, text = "巨狼雙魂", sealwareId = 200110008 	},
		{ sort = 9, text = "阿爾忒彌斯之弓", sealwareId = 200110009 	},
		{ sort = 10, text = "拉神寶球", sealwareId = 200110010 	},
		{ sort = 11, text = "原初之眼", sealwareId = 200110011 	},
		{ sort = 12, text = "永恆之槍", sealwareId = 200110012 	},
		{ sort = 13, text = "雷霆之盾", sealwareId = 200210001 	},
		{ sort = 14, text = "鮮血聖杯", sealwareId = 200210002 	},
		{ sort = 15, text = "佛拉格拉克", sealwareId = 200210003 	},
		{ sort = 16, text = "世界樹根", sealwareId = 200210004 	},
		{ sort = 17, text = "死靈之書", sealwareId = 200210005 	},
		{ sort = 18, text = "妖精之弓希爾文", sealwareId = 200210006 	},
		{ sort = 19, text = "龍之寶玉奧普", sealwareId = 200210007 	},
		{ sort = 20, text = "赫格尼之劍", sealwareId = 200210008 	},
		{ sort = 21, text = "烈焰之劍雷沃汀", sealwareId = 200210009 	},
		{ sort = 22, text = "神王雷槍", sealwareId = 200210010 	},
		{ sort = 23, text = "雙蛇權杖", sealwareId = 200210011 	},
		{ sort = 24, text = "蛇骨短劍", sealwareId = 200210012 	},
		{ sort = 25, text = "羊靈頭顱", sealwareId = 200210013 	},
		{ sort = 26, text = "方舟龍骨", sealwareId = 200210014 	},
		{ sort = 27, text = "巨獸犄角", sealwareId = 200210015 	},
		{ sort = 28, text = "鑽頭劍", sealwareId = 200210016 	},
		{ sort = 29, text = "伊利丹爾古", sealwareId = 200210017 	},
		{ sort = 30, text = "鹿靈頭骨", sealwareId = 200210018 	},
		{ sort = 31, text = "靈魂燈籠", sealwareId = 200210019 	},
		{ sort = 32, text = "末地寶珠", sealwareId = 200210020 	},
		{ sort = 33, text = "帶刺炎尾", sealwareId = 200210021 	},
		{ sort = 34, text = "胡狼頭盔", sealwareId = 200210022 	},
		{ sort = 35, text = "隼型頭盔", sealwareId = 200210023 	},
		{ sort = 36, text = "石質蛇首", sealwareId = 200210024 	},
		{ sort = 37, text = "神秘戒指", sealwareId = 200210025 	},
		{ sort = 38, text = "金質聖甲蟲", sealwareId = 200210026 	},
		{ sort = 39, text = "銜尾蛇戒指", sealwareId = 200210027 	},
		{ sort = 40, text = "懷特的髕骨", sealwareId = 200210028 	},
		{ sort = 41, text = "妖狐面具", sealwareId = 200210029 	},
		{ sort = 42, text = "血魔披風", sealwareId = 200210030 	},
		{ sort = 43, text = "神秘名單", sealwareId = 200210031 	},
		{ sort = 44, text = "渡鴉羽毛", sealwareId = 200210032 	},
		{ sort = 45, text = "詭異石盤", sealwareId = 200210033 	},
		{ sort = 46, text = "水晶頭骨", sealwareId = 200210034 	},
		{ sort = 47, text = "人身獅面像", sealwareId = 200210035 	},
		{ sort = 48, text = "海妖豎琴", sealwareId = 200210036 	},
		{ sort = 49, text = "賽巴的石頭", sealwareId = 200210037 	},
		{ sort = 50, text = "雷獸利角", sealwareId = 200210038 	},
		{ sort = 51, text = "魔龍毒牙", sealwareId = 200210039 	},
		{ sort = 52, text = "瓶裝龍息", sealwareId = 200210040 	},
		{ sort = 53, text = "透明蟲翅", sealwareId = 200210041 	},
		{ sort = 54, text = "地精戰錘", sealwareId = 200210042 	},
		{ sort = 55, text = "精靈短弓", sealwareId = 200210043 	},
		{ sort = 56, text = "捕夢網", sealwareId = 200210044 	},
		{ sort = 57, text = "酒館鑰匙", sealwareId = 200210045 	},
		{ sort = 58, text = "詭異布偶", sealwareId = 200210046 	},
		{ sort = 59, text = "黃金鎧甲", sealwareId = 200210047 	},
		{ sort = 60, text = "星座紋章", sealwareId = 200210048 	},
		{ sort = 61, text = "銘文石碑", sealwareId = 200210049 	},
		{ sort = 62, text = "花生狀石塊", sealwareId = 200210050 	}
	}

}


---@type table<number, FightCommandDefine>
tab.FightCommandBysort = {}
for _, rec in pairs(tab.FightCommand) do
	tab.FightCommandBysort[rec.sort] = rec
end

---@type table<number, GoodsCommandDefine>
tab.GoodsCommandBysort = {}
for _, rec in pairs(tab.GoodsCommand) do
	tab.GoodsCommandBysort[rec.sort] = rec
end

---@type table<number, TestSheetDefine>
tab.TestSheetBysort = {}
for _, rec in pairs(tab.TestSheet) do
	tab.TestSheetBysort[rec.sort] = rec
end

---@type table<number, TestCommandDefine>
tab.TestCommandBysort = {}
for _, rec in pairs(tab.TestCommand) do
	tab.TestCommandBysort[rec.sort] = rec
end

---@type table<number, SealwareCommandDefine>
tab.SealwareCommandBysort = {}
for _, rec in pairs(tab.SealwareCommand) do
	tab.SealwareCommandBysort[rec.sort] = rec
end

---@type table<number, LevelCommandDefine>
tab.LevelCommandBysort = {}
for _, rec in pairs(tab.LevelCommand) do
	tab.LevelCommandBysort[rec.sort] = rec
end

---@type table<number, TestCommand2Define>
tab.TestCommand2Bysort = {}
for _, rec in pairs(tab.TestCommand2) do
	tab.TestCommand2Bysort[rec.sort] = rec
end

tab.Enum = {
}

return tab